driver:
   name: vagrant

provisioner:
   name: chef_zero

verifier:
   name: inspec

platforms:
   - name: centos-7.2

suites:
  - name: web
    driver:
        network:
           - ["private_network", { ip: '172.16.0.11' }]
        synced_folders:
           - ["/Users/ricknaik/Documents/php", "/var/www", {owner: "root"}, "create: true, type: :nfs, dmode=777, fmode=777"]
    run_list:
      - recipe[lamp::default]
    attributes:
      local_kitchen: true
      httpd:
        enabled: true
      php:
        enabled: true
      mariadb:
        enabled: false
  - name: db
    driver:
        network:
           - ["private_network", { ip: '172.16.0.12' }]
    run_list:
      - recipe[lamp::default]
    attributes:
      local_kitchen: true
      httpd:
        enabled: false
      php:
        enabled: false
      mariadb:
        enabled: true