driver:
   name: vagrant
   network:
     - ["forwarded_port", { guest: 80, host: 8080 }]
     - ["forwarded_port", { guest: 443, host: 8443 }]
     - ["forwarded_port", { guest: 3306, host: 8306 }]
     #- ["private_network", { ip: "192.168.33.10"}]
   #synced_folders:
     #- ["C:", "/var/www", {owner: "root"}, "create: true, type: :nfs, dmode=777, fmode=777"]

provisioner:
   name: chef_zero

verifier:
   name: inspec

platforms:
   - name: centos-7.2

suites:
  - name: web
    run_list:
      - recipe[lamp::default]
    attributes:
      httpd:
        enabled: true
      php:
        enabled: true
      mariadb:
        enabled: false
  - name: db
    run_list:
      - recipe[lamp::default]
    attributes:
      httpd:
        enabled: false
      php:
        enabled: false
      mariadb:
        enabled: true